import { Colors } from "../colors.types";
import { addAlpha, primitiveColors } from "./primitiveColors";

export const colorDark: Colors = {
  // color
  primary: primitiveColors.JuGreen400,
  onPrimary: primitiveColors.JuNavy,
  secondary: primitiveColors.JuOrange300,
  onSecondary: primitiveColors.BgNavy2,
  tertiary: primitiveColors.JuCyan200,
  onTertiary: primitiveColors.BgNavy2,
  error: primitiveColors.JuAlertRed400,
  onError: primitiveColors.BgNavy2,
  selector: primitiveColors.JuGreen300,
  selectorDisabled: addAlpha(primitiveColors.JuGreen300, "30%"),
  success: primitiveColors.JuGreen300,
  suggest: primitiveColors.JuOrange300,
  sectionHeader: primitiveColors.JuOrange300,

  // text color
  primaryText: addAlpha(primitiveColors.JuWhite, "87%"),
  secondaryText: addAlpha(primitiveColors.JuWhite, "60%"),
  tertiaryDisabledText: addAlpha(primitiveColors.JuWhite, "38%"),
  hyperlinksText: primitiveColors.JuGreen300,
  emphasisText: primitiveColors.JuOrange300,
  alertText: primitiveColors.JuAlertRed400,
  alertTextDisabled: addAlpha(primitiveColors.JuAlertRed400, "38%"),
  brandPrimaryText: primitiveColors.JuNavy,
  brandPrimaryDisabledText: addAlpha(primitiveColors.JuNavy, "42%"),
  brandSecondaryText: addAlpha(primitiveColors.JuNavy, "70%"),
  inverseText: primitiveColors.JuNavy,
  inverseTextSecondary: addAlpha(primitiveColors.JuNavy, "70%"),
  onDarkText: primitiveColors.JuWhite,

  // background
  background: primitiveColors.BaseNavy,
  backgroundSurface: primitiveColors.BgNavy2,
  backgroundSurfaceBright: primitiveColors.BgNavy4,
  backgroundSubtlest: primitiveColors.BgNavy1,
  backgroundSubtler: primitiveColors.BgNavy1,
  backgroundSubtle: primitiveColors.BgNavy2,
  backgroundBold: primitiveColors.BgNavy3,
  backgroundBolder: primitiveColors.BgNavy4,
  backgroundBoldest: primitiveColors.BgNavy6,
  backgroundSuggest: primitiveColors.BgNavy4,
  backgroundDanger: primitiveColors.JuAlertRed400,
  backgroundDangerHover: addAlpha(primitiveColors.JuAlertRed400, "70%"),
  backgroundDangerDisabled: addAlpha(primitiveColors.JuAlertRed400, "50%"),
  backgroundDangerPressed: primitiveColors.JuAlertRed600,
  backgroundDangerTextHover: addAlpha(primitiveColors.JuAlertRed400, "30%"),
  backgroundDangerTextPressed: addAlpha(primitiveColors.JuAlertRed400, "70%"),
  backgroundAlert: addAlpha(primitiveColors.JuAlertRed400, "30%"),
  backgroundAlertBolder: addAlpha(primitiveColors.JuAlertRed400, "90%"),
  backgroundPrimary: primitiveColors.JuGreen400,
  backgroundPrimaryHover: addAlpha(primitiveColors.JuGreen400, "70%"),
  backgroundPrimaryPressed: primitiveColors.JuGreen600,
  backgroundPrimaryDisabled: addAlpha(primitiveColors.JuGreen400, "50%"),
  backgroundNeutral: primitiveColors.BgNavy4,
  backgroundNatureHover: addAlpha(primitiveColors.JuCyan200, "30%"),
  backgroundNaturePressed: addAlpha(primitiveColors.JuCyan200, "90%"),
  backgroundMenuHover: addAlpha(primitiveColors.JuCyan200, "10%"),
  backgroundMenuPressed: addAlpha(primitiveColors.JuCyan200, "30%"),
  backgroundMenuSelected: addAlpha(primitiveColors.JuCyan200, "30%"),
  backgroundChipGiftItLater: addAlpha(primitiveColors.JuOrange300, "30%"),
  backgroundChipGift: addAlpha(primitiveColors.JuCyan200, "30%"),
  backgroundChipGray: primitiveColors.BgNavy3,
  backgroundChipBlue: addAlpha(primitiveColors.JuCyan200, "30%"),
  backgroundChipOrange: addAlpha(primitiveColors.JuOrange300, "30%"),
  backgroundChipGreen: addAlpha(primitiveColors.JuGreen400, "30%"),
  backgroundActive: primitiveColors.BgNavy6,
  backgroundDefault: primitiveColors.BgNavy2,
  backgroundPrimaryDark: primitiveColors.JuGreen300,
  backgroundSecondary: primitiveColors.JuOrange300,
  backgroundTertiary: primitiveColors.JuCyan200,
  backgroundInverse: primitiveColors.JuWhite,
  backgroundInverseSubtle: addAlpha(primitiveColors.JuCyan200, "70%"),
  backgroundBackdrop: addAlpha(primitiveColors.JuNavy, "50%"),
  backgroundGift: primitiveColors.BgNavy3,
  backgroundOnDark: primitiveColors.JuWhite,
  backgroundReview: addAlpha(primitiveColors.JuOrange300, "30%"),
  backgroundUpdated: addAlpha(primitiveColors.JuGreen400, "10%"),
  backgroundSegmentedControlButtonHover: addAlpha(
    primitiveColors.JuCyan200,
    "30%"
  ),
  backgroundSegmentedControlButtonPressed: addAlpha(
    primitiveColors.JuCyan200,
    "30%"
  ),
  backgroundTableHead: primitiveColors.BgNavy4,
  backgroundLabelCyan: primitiveColors.JuCyan400,
  backgroundLabelOrange: primitiveColors.JuOrange300,
  backgroundLabelGrey: primitiveColors.BgGray3,
  backgroundLabelPink: "#F186C0",

  // border
  border: addAlpha(primitiveColors.JuCyan200, "15%"),
  borderBold: addAlpha(primitiveColors.JuWhite, "60%"),
  borderBoldDisabled: addAlpha(primitiveColors.JuWhite, "38%"),
  borderInput: addAlpha(primitiveColors.JuWhite, "38%"),
  borderInputActive: primitiveColors.JuGreen900,
  borderInputDisabled: addAlpha(primitiveColors.JuCyan200, "15%"),
  borderInputError: primitiveColors.JuAlertRed400,
  borderActive: primitiveColors.JuGreen300,
  borderInactive: addAlpha(primitiveColors.JuCyan200, "15%"),
  borderChipGray: addAlpha(primitiveColors.JuWhite, "60%"),
  borderChipBlue: primitiveColors.JuCyan200,
  borderChipOrange: primitiveColors.JuOrange300,
  borderChipGreen: primitiveColors.JuGreen400,
  borderOnLight: addAlpha(primitiveColors.JuNavy, "15%"),
  borderLabelDefault: primitiveColors.JuGreen900,
  borderLabelCyan: primitiveColors.JuCyan400,
  borderLabelOrange: primitiveColors.JuOrange300,
  borderLabelGrey: primitiveColors.BgGray3,
  borderLabelPink: "#F186C0",
};
