---
services:
  storybook:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: tmhub-design-system-react
    tty: true
    working_dir: /app
    command: sh -c 'yarn install && yarn storybook'
    environment:
      BROWSER: true
      WATCHPACK_POLLING: true
    volumes:
      - ..:/app
      - $HOME/.ssh:/root/.ssh
    ports:
      - "6006:6006"
