import { createGlobalTheme, createThemeContract } from "@vanilla-extract/css";
import { spacing } from "../../shared/tokens/spacing";

const base = createGlobalTheme(".tmhub-design-system-root", {
  spacing: {
    none: `${spacing.none}px`,
    "3xs": `${spacing["3xs"]}px`,
    "2xs": `${spacing["2xs"]}px`,
    xs: `${spacing.xs}px`,
    sm: `${spacing.sm}px`,
    md: `${spacing.md}px`,
    lg: `${spacing.lg}px`,
    xl: `${spacing.xl}px`,
    "2xl": `${spacing["2xl"]}px`,
    "3xl": `${spacing["3xl"]}px`,
    "4xl": `${spacing["4xl"]}px`,
    "5xl": `${spacing["5xl"]}px`,
    "6xl": `${spacing["6xl"]}px`,
    "7xl": `${spacing["7xl"]}px`,
    "8xl": `${spacing["8xl"]}px`,
  },
  container: {
    maxWidthXs: "448px",
    maxWidthSm: "688px",
    maxWidthMd: "880px",
    maxWidthLg: "1136px",
    maxWidthFull: "100%",
  },
});

export const color = createThemeContract({
  // Light =====================================================
  // color
  primaryLight: "",
  onPrimaryLight: "",
  secondaryLight: "",
  onSecondaryLight: "",
  tertiaryLight: "",
  onTertiaryLight: "",
  errorLight: "",
  onErrorLight: "",
  selectorLight: "",
  selectorDisabledLight: "",
  successLight: "",
  suggestLight: "",
  sectionHeaderLight: "",

  // text color
  primaryTextLight: "",
  secondaryTextLight: "",
  tertiaryDisabledTextLight: "",
  hyperlinksTextLight: "",
  emphasisTextLight: "",
  alertTextLight: "",
  brandPrimaryTextLight: "",
  brandPrimaryDisabledTextLight: "",
  brandSecondaryTextLight: "",
  inverseTextLight: "",
  inverseTextSecondaryLight: "",
  onDarkTextLight: "",

  // background
  backgroundLight: "",
  backgroundSurfaceLight: "",
  backgroundSurfaceBrightLight: "",
  backgroundSubtlestLight: "",
  backgroundSubtlerLight: "",
  backgroundSubtleLight: "",
  backgroundBoldLight: "",
  backgroundBolderLight: "",
  backgroundBoldestLight: "",
  backgroundSuggestLight: "",
  backgroundAlertLight: "",
  backgroundAlertBolderLight: "",
  backgroundPrimaryLight: "",
  backgroundPrimaryHoverLight: "",
  backgroundPrimaryPressedLight: "",
  backgroundPrimaryDisabledLight: "",
  backgroundNeutralLight: "",
  backgroundNatureHoverLight: "",
  backgroundNaturePressedLight: "",
  backgroundMenuHoverLight: "",
  backgroundMenuSelectedLight: "",
  backgroundChipGiftItLaterLight: "",
  backgroundChipGiftLight: "",
  backgroundTagChipGrayLight: "",
  backgroundTagChipBlueLight: "",
  backgroundTagChipOrangeLight: "",
  backgroundTagChipGreenLight: "",
  backgroundActiveLight: "",
  backgroundDefaultLight: "",
  backgroundPrimaryDarkLight: "",
  backgroundSecondaryLight: "",
  backgroundTertiaryLight: "",
  backgroundInverseLight: "",
  backgroundInverseSubtleLight: "",
  backgroundBackdropLight: "",
  backgroundGiftLight: "",
  backgroundOnDarkLight: "",
  backgroundReviewLight: "",
  backgroundUpdatedLight: "",
  backgroundSegmentedControlButtonHoverLight: "",
  backgroundSegmentedControlButtonPressedLight: "",
  backgroundTableHeadLight: "",
  backgroundLabelCyanLight: "",
  backgroundLabelOrangeLight: "",
  backgroundLabelGreyLight: "",
  backgroundLabelPinkLight: "",

  // border
  borderLight: "",
  borderBoldLight: "",
  borderBoldDisabledLight: "",
  borderInputLight: "",
  borderInputActiveLight: "",
  borderInputDisabledLight: "",
  borderInputErrorLight: "",
  borderActiveLight: "",
  borderInactiveLight: "",
  borderTagChipGrayLight: "",
  borderTagChipBlueLight: "",
  borderTagChipOrangeLight: "",
  borderTagChipGreenLight: "",
  borderOnLightLight: "",
  borderLabelDefaultLight: "",
  borderLabelCyanLight: "",
  borderLabelOrangeLight: "",
  borderLabelGreyLight: "",
  borderLabelPinkLight: "",

  // Dark =====================================================
  // color
  primaryDark: "",
  onPrimaryDark: "",
  secondaryDark: "",
  onSecondaryDark: "",
  tertiaryDark: "",
  onTertiaryDark: "",
  errorDark: "",
  onErrorDark: "",
  selectorDark: "",
  selectorDisabledDark: "",
  successDark: "",
  suggestDark: "",
  sectionHeaderDark: "",

  // text color
  primaryTextDark: "",
  secondaryTextDark: "",
  tertiaryDisabledTextDark: "",
  hyperlinksTextDark: "",
  emphasisTextDark: "",
  alertTextDark: "",
  brandPrimaryTextDark: "",
  brandPrimaryDisabledTextDark: "",
  brandSecondaryTextDark: "",
  inverseTextDark: "",
  inverseTextSecondaryDark: "",
  onDarkTextDark: "",

  // background
  backgroundDark: "",
  backgroundSurfaceDark: "",
  backgroundSurfaceBrightDark: "",
  backgroundSubtlestDark: "",
  backgroundSubtlerDark: "",
  backgroundSubtleDark: "",
  backgroundBoldDark: "",
  backgroundBolderDark: "",
  backgroundBoldestDark: "",
  backgroundSuggestDark: "",
  backgroundAlertDark: "",
  backgroundAlertBolderDark: "",
  backgroundPrimaryDark: "",
  backgroundPrimaryHoverDark: "",
  backgroundPrimaryPressedDark: "",
  backgroundPrimaryDisabledDark: "",
  backgroundNeutralDark: "",
  backgroundNatureHoverDark: "",
  backgroundNaturePressedDark: "",
  backgroundMenuHoverDark: "",
  backgroundMenuSelectedDark: "",
  backgroundChipGiftItLaterDark: "",
  backgroundChipGiftDark: "",
  backgroundTagChipGrayDark: "",
  backgroundTagChipBlueDark: "",
  backgroundTagChipOrangeDark: "",
  backgroundTagChipGreenDark: "",
  backgroundActiveDark: "",
  backgroundDefaultDark: "",
  backgroundPrimaryDarkDark: "",
  backgroundSecondaryDark: "",
  backgroundTertiaryDark: "",
  backgroundInverseDark: "",
  backgroundInverseSubtleDark: "",
  backgroundBackdropDark: "",
  backgroundGiftDark: "",
  backgroundOnDarkDark: "",
  backgroundReviewDark: "",
  backgroundUpdatedDark: "",
  backgroundSegmentedControlButtonHoverDark: "",
  backgroundSegmentedControlButtonPressedDark: "",
  backgroundTableHeadDark: "",
  backgroundLabelCyanDark: "",
  backgroundLabelOrangeDark: "",
  backgroundLabelGreyDark: "",
  backgroundLabelPinkDark: "",

  // border
  borderDark: "",
  borderBoldDark: "",
  borderBoldDisabledDark: "",
  borderInputDark: "",
  borderInputActiveDark: "",
  borderInputDisabledDark: "",
  borderInputErrorDark: "",
  borderActiveDark: "",
  borderInactiveDark: "",
  borderTagChipGrayDark: "",
  borderTagChipBlueDark: "",
  borderTagChipOrangeDark: "",
  borderTagChipGreenDark: "",
  borderOnLightDark: "",
  borderLabelDefaultDark: "",
  borderLabelCyanDark: "",
  borderLabelOrangeDark: "",
  borderLabelGreyDark: "",
  borderLabelPinkDark: "",

  // General =====================================================
  inherit: "",
  transparent: "",
});

export const vars = { ...base, color };
