import type { Metadata } from "next";
import "./globals.css";
import { DesignProvider } from 'tmhub-design-system-react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DesignProvider theme="teamhub" asChild>
        <body>
          {children}
        </body>
      </DesignProvider>
    </html>
  );
}
